name: Build

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew shadowJar

      - name: Upload build artifacts velocity
        uses: actions/upload-artifact@v3
        with:
          name: velocity-build
          path: netman-velocity/build/libs

      - name: Upload build artifacts spigot
        uses: actions/upload-artifact@v3
        with:
          name: spigot-build
          path: netman-spigot/build/libs
